### 帮助文档    https://blog.csdn.net/M_Q_L_/article/details/104895135
#######################################################################################
### 模拟登陆请求
POST {{baseUrl}}/sso/mock/login
Content-Type: application/json

{
  "email": "hyman.li@zenlayer.com",
  "expireMin": 720
}

> {%
    client.global.set("authToken", response.body.data.token);
%}

###
GET {{baseUrl}}/device/deviceTest

###
GET localhost:8080/productUser/queryList

####
POST localhost:8080/productUser/update
Content-Type: application/json

{
  "id": 1,
  "passWord": "edit_1",
  "userName": "edit_aaron"
}

###############################################################################

GET localhost:8088/device/queryBssNewInstance/FLOW690143474015588448
Content-Type: application/json

##################

localhost:8088/excel/excelExport?bizCode=AP-DETAIL-REPORT-BIZ&requestParamJson=%7B%22queryValue%22%3A%22%22%2C%22pageNum%22%3A1%2C%22pageSize%22%3A2%7D
Content-Type: application/json

##################

localhost:8088/device/existPreQuoteChange
Content-Type: application/json

##################
localhost:8088/excel/queryParamDicList
Content-Type: application/json

##################
