### 帮助文档    https://blog.csdn.net/M_Q_L_/article/details/104895135
#######################################################################################
### 模拟登陆请求
POST {{baseUrl}}/sso/mock/login
Content-Type: application/json

{
  "email": "hyman.li@zenlayer.com",
  "expireMin": 720
}

> {%
    client.global.set("authToken", response.body.data.token);
%}

###
GET {{baseUrl}}/device/deviceTest

###
GET localhost:8080/productUser/queryList

####
POST localhost:8080/productUser/update
Content-Type: application/json

{
  "id": 1,
  "passWord": "edit_1",
  "userName": "edit_aaron"
}

### END ###############################################################################